language: ruby
rvm:
- 1.9.3
- 2.0
- 2.1
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
