[package]
name = "classifier_reborn"
authors = ["Chase Gilliam"]
repository = "https://github.com/jekyll/classifier-reborn"
version = "2.1.0"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
ruru = "0.9.2"
la = "0.2.0"
